-- Desactivar revisión de llaves foráneas para poder hacer Truncate
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE encuestas;
TRUNCATE TABLE subdimensiones;
TRUNCATE TABLE preguntas;

-- Insertar las preguntas desde el Excel considerando Tabla Sub-Dimensiones (encuesta_id = 1 por defecto)
INSERT INTO encuestas (titulo, descripcion) VALUES ('Diagnóstico Inicial', 'Cuestionario base extraído del Excel');

-- Inserción de tabla Subdimensiones
INSERT INTO subdimensiones (id, dimension_id, nombre, orden) VALUES 
(1, 1, 'General', 1),
(2, 1, 'Liderazgo', 1),
(3, 1, 'Cultura Organizacional', 6),
(4, 2, 'General', 1),
(5, 2, 'Proceso de Planeación Táctica', 11),
(6, 2, 'Innovación de Productos, Procesos y Servicios', 19),
(7, 3, 'General', 1),
(8, 3, 'Inteligencia de Mercado', 1),
(9, 3, 'Compromiso y Satisfacción', 8),
(10, 4, 'General', 1),
(11, 4, 'Administración Estratégica de Recursos Humanos', 1),
(12, 4, 'Captación de Talento', 3),
(13, 4, 'Desarrollo de Talento Humano', 6),
(14, 4, 'Sistemas de Trabajo', 10),
(15, 5, 'General', 1),
(16, 5, 'Diseño y Desarrollo de Productos, Procesos y/o Servicios', 1),
(17, 6, 'General', 1),
(18, 6, 'Control de Procesos', 1),
(19, 6, 'Administración del Conocimiento', 8),
(20, 7, 'General', 1),
(21, 7, 'Selección y Desarrollo de Proveedores', 1),
(22, 8, 'General', 1),
(23, 9, 'General', 1),
(24, 9, 'Factores de Seguridad y Salud', 1),
(25, 9, 'Factores del Desempeño en el Puesto', 9),
(26, 9, 'Factores del Equilibrio Laboral / Familiar', 14),
(27, 9, 'Factores de Carrera Laboral', 16),
(28, 10, 'General', 1),
(29, 10, 'Resiliencia y Gestión de Entornos', 1);

-- Inserción de tabla Preguntas
INSERT INTO preguntas (encuesta_id, dimension_id, subdimension_id, texto_pregunta, orden) VALUES 
(1, 1, 2, 'a) Existe un alto involucramiento de la Dirección y Gerencia en asumir, apoyar e implementar prácticas para la calidad, la excelencia de operación, la mejora continua, la disrupción de negocio y la innovación.', 1),
(1, 1, 2, 'b) Las prácticas de liderazgo están implementadas en los diferentes niveles de la organización.', 2),
(1, 1, 2, 'c) La Dirección y Gerencia se aseguran de cumplir con los requisitos legales, normativos y regulatorios vinculados a la organización.', 3),
(1, 1, 2, 'd) La Dirección y Gerencia se aseguran de contribuir y/o gestionar la administración del cambio en la Organización de forma estratégica, observable, gradual y medible.', 4),
(1, 1, 2, 'e) La Dirección y Gerencia se aseguran de integrar y gestionar las directrices de negocio encaminadas a mantener la cadena de valor del negocio de forma sustentable.', 5),
(1, 1, 3, 'f) Cuenta la organización con descripción de la Misión, Visión, Valores.', 6),
(1, 1, 3, 'g) Se enuncia, promueve y asegura el comportamiento ético en la organización (a través de por ejemplo un código de ética, o reglamento, o procedimientos, o normas).', 7),
(1, 1, 3, 'h) Se cuenta con prácticas generalizadas para promover la Creatividad, Innovación y la Mejora Continua en la organización.', 8),
(1, 1, 3, 'i) Se cuenta con mecanismos que se utilizan para obtener una comunicación efectiva en la organización.', 9),
(1, 2, 4, 'Proceso de Planeación Estratégica (corto, mediano y largo plazo)', 1),
(1, 2, 4, 'a) Se cuenta con un proceso de planeación estratégica con un horizonte de al menos 3 años, contemplando diferentes escenarios de actuación con base a las variables internas y externas y se revisa anualmente.', 2),
(1, 2, 4, 'b) En el proceso de planeación se revisan y actualizan los elementos de la filosofía organizacional', 3),
(1, 2, 4, 'c) En el proceso de planeación se analiza la información sobre el sector y sus competidores principales (análisis competitivo), determinando brechas en productos y servicios en materia de precios, condiciones de venta, calidad, atributos, posibilidades de nuevos competidores y prácticas de negocio, tanto en la posición estratégica actual como en la futura de la Organización.', 4),
(1, 2, 4, 'd) En el proceso de planeación se integra información relativa al desempeño de la organización: mercado, análisis competitivo, calidad, servicio, financiera, recurso humano, productividad, impacto ambiental.', 5),
(1, 2, 4, 'e) En su proceso de planeación se incluyen las proyecciones socioeconómicas del entorno, así como las tendencias globales, al mediano y largo plazo.', 6),
(1, 2, 4, 'f) En su proceso de planeación se integra la información de clientes: Se tiene identificado el tamaño del mercado, su participación y evolución.', 7),
(1, 2, 4, 'g) En su proceso de planeación se integra la información relativa a proveedores, tales como: tendencia en precios, confiabilidad, logística, oferta, entre otros.', 8),
(1, 2, 4, 'h) En la organización se tienen definidos los factores clave de éxito y se les da seguimiento.', 9),
(1, 2, 4, 'i) En su proceso de planeación se incluye el análisis para el desarrollo de nuevos negocios (Diversificación / Disrupción).', 10),
(1, 2, 5, 'j) A partir del proceso de planeación estratégica, la organización cuenta con prácticas utilizadas para la definición de los objetivos, metas (cuantificables) y planes de acción tácticos.', 11),
(1, 2, 5, 'k) Se cuenta con modelo de negocio que incluye la determinación de ingresos, egresos, capital de trabajo, cálculo de inversiones, recurso humano y en su caso requerimiento de recursos financieros.', 12),
(1, 2, 5, 'l) La organización cuenta con mecanismos para asegurar la efectiva ejecución de sus planes de acción tácticos y cumplimiento de metas.', 13),
(1, 2, 5, 'm) En la organización se promueve y se ha protegido la creación de nuevos productos, servicios y/o marcas.', 14),
(1, 2, 5, 'n) La organización cuenta con un mecanismo para la administración y gestión de los costos y gastos de la organización en cada uno de sus subsistemas organizacionales.', 15),
(1, 2, 5, 'o) La organización cuenta con un mecanismo o mejores prácticas para mejorar la eficiencia de su proceso de producción / operación.', 16),
(1, 2, 5, 'p) La organización cuenta con mejores prácticas para la administración y seguimiento del desempeño financiero y fiscal.', 17),
(1, 2, 5, 'q) La organización cuenta con mejores prácticas para la administración de inventarios / almacenes / insumos.', 18),
(1, 2, 6, 'r) La innovación de los productos, procesos y servicios está alineada a las estrategias de la organización.', 19),
(1, 2, 6, 's) Se cuenta con una descripción clara de las necesidades y expectativas de los clientes, para planear la innovación de sus productos, procesos y servicios.', 20),
(1, 3, 8, 'a) Se tienen identificados los segmentos de mercados / clientes / servicios / rentabilidad / estratificación de la cartera de clientes a través de prácticas de Inteligencia Comercial.', 1),
(1, 3, 8, 'b) Se cuenta con una estrategia de mercadotecnia para atraer clientes y desarrollar nuevos mercados para posicionar a la organización en sus diferentes segmentos de mercados.', 2),
(1, 3, 8, 'c) Se cuenta con métodos para identificar las necesidades actuales y futuras de los diferentes segmentos de mercados / clientes / servicios / rentabilidad. Incluyendo entre otros: precios, canales de distribución, términos y condiciones de venta.', 3),
(1, 3, 8, 'd) La organización se asegura de cumplir con los requerimientos de los clientes / usuarios, previo a la contratación del producto y/o servicio.', 4),
(1, 3, 8, 'e) La organización incorpora las necesidades y/o requerimientos de los clientes / usuarios a los procesos de negocio.', 5),
(1, 3, 8, 'f) Se cuenta con un sistema integral de calidad enfocado a los clientes.', 6),
(1, 3, 8, 'g) Se cuenta con un modelo y/o mejor práctica para establecer relaciones de negocio a largo plazo con los clientes.', 7),
(1, 3, 9, 'h) Se cuenta con una descripción de los compromisos de calidad y servicio con los clientes / usuarios.', 8),
(1, 3, 9, 'i) Se cuenta con un proceso para conocer el grado de satisfacción de los clientes / usuarios.', 9),
(1, 3, 9, 'j) La organización incorpora la información de satisfacción de sus clientes / usuarios a los procesos de negocio.', 10),
(1, 3, 9, 'k) Se cuenta con un proceso para asegurar la recuperación de los clientes / usuarios perdidos. (Postventa / Venta Cruzada)', 11),
(1, 3, 9, 'l) Se cuenta con un proceso para asegurar la atención efectiva de sugerencias, quejas formales e informales.', 12),
(1, 4, 11, 'a) Se cuenta con un Plan Estratégico de Recursos Humanos (PERH) a partir de los Objetivos Estratégicos de la Organización.', 1),
(1, 4, 11, 'b) Se cuentan con mejores prácticas de Recursos Humanos en: Gestión Estratégica de RRHH, Administración de RRHH, Desarrollo de RRHH, Gestión de la Productividad de RRHH, Operación de RRHH y Relaciones Laborales.', 2),
(1, 4, 12, 'c) A partir del plan estratégico y del análisis de los procesos son definidos los puestos, así como sus requerimientos en toda la organización.', 3),
(1, 4, 12, 'd) Se cuenta con un proceso formal de captación, reclutamiento y selección y retención de talento humano alineado a los requerimientos estratégicos definidos.', 4),
(1, 4, 12, 'e) Se cuenta con un proceso de inducción formal para el talento humano.', 5),
(1, 4, 13, 'f) Se cuenta con un proceso para detectar las necesidades de capacitación y desarrollo enfocadas a las estrategias de la organización.', 6),
(1, 4, 13, 'g) Se cuenta con programas de capacitación y desarrollo del talento humano.', 7),
(1, 4, 13, 'h) Se cuenta con un proceso de evaluación y/o gestión del desempeño y retroalimentación del talento humano.', 8),
(1, 4, 13, 'i) Se cuenta con mecanismos de reconocimiento y compensación al talento humano alineados a la evaluación del desempeño y a la productividad.', 9),
(1, 4, 14, 'j) Se cuenta con métodos para promover el involucramiento del talento humano en el logro de los objetivos, tanto en forma individual como grupal.', 10),
(1, 4, 14, 'k) Se cuenta con prácticas para asegurar que las condiciones de trabajo sean adecuadas y acordes a normativas aplicables a su organización: seguridad e higiene industrial', 11),
(1, 4, 14, 'l) Se cuenta con mecanismos para evaluar la satisfacción del talento humano.', 12),
(1, 4, 14, 'm) Se cuenta con mecanismos que contribuyen a fomentar el bienestar del talento humano.', 13),
(1, 5, 16, 'a) Se cuenta con un proceso para el diseño y modificación de productos, procesos y /o servicios.', 1),
(1, 5, 16, 'b) Se cuenta con mecanismos para verificar que el diseño de productos, procesos y/o servicios cumplan con los requerimientos del cliente y la normatividad aplicable previo a su liberación.', 2),
(1, 5, 16, 'c) Se cuenta con mecanismos para asegurar que el nuevo diseño del producto, proceso y/o servicio esté libre de fallas durante su operación. Algunos medios pueden ser: simulaciones, pruebas, prototipos, modelaciones, entre otros.', 3),
(1, 5, 16, 'd) Se cuenta con mecanismos para implementar y/o transferir los diseños de los productos, procesos y/o servicios a las áreas involucradas.', 4),
(1, 5, 16, 'e) Se cuentan con mejores prácticas para la optimización de la operación / producción a través de la definición, documentación, análisis, actualización y/o mejora y comunicación de los procesos de negocio de la empresa.', 5),
(1, 6, 18, 'a) Se cuenta con clara definición del Macroproceso Organización incluyendo sus indicadores de desempeño.', 1),
(1, 6, 18, 'b) Se cuenta con clara definición de los procesos básicos en la organización incluyendo sus indicadores de desempeño.', 2),
(1, 6, 18, 'c) Se cuenta con un proceso establecido para el suministro, transporte, almacenaje y aprovechamiento óptimo de los insumos.', 3),
(1, 6, 18, 'd) Se cuenta con equipo e instalaciones adecuadas para la operación, así como un programa de mantenimiento que asegure su integridad, operación y seguridad en uso.', 4),
(1, 6, 18, 'e) Se cuenta con sistemas de operación que asegure: flexibilidad, minimice desperdicios y retrabajos, reduzca tiempo de ciclos, aumente la productividad del personal y activos.', 5),
(1, 6, 18, 'f) Se cuenta con procesos para la administración y control de la documentación de la operación, tales como: facturación, órdenes de compra, registros de operación, pólizas contables, entre otros.', 6),
(1, 6, 18, 'g) Se cuenta con mecanismos de control de los procesos básicos.', 7),
(1, 6, 19, 'h) Se utiliza la información generada por los mecanismos de control para asegurar que el desempeño de los procesos permita cumplir los requerimientos de diseño.', 8),
(1, 6, 19, 'i) Se cuenta con métodos para evaluar, analizar y mejorar los procesos', 9),
(1, 6, 19, 'j) Se cuenta con prácticas para asegurar la continuidad de los procesos en situaciones de contingencia en los que pueda verse interrumpido el proceso, producto o servicio.', 10),
(1, 6, 19, 'k) Se cuenta con mecanismos para mantener y proteger la información derivada de la administración y seguimiento de los procesos.', 11),
(1, 6, 19, 'l) Se cuenta con mecanismos para mantener y proteger el conocimiento tanto el de la operación, así como, el generado a partir de la Innovación y Mejora Continua en la organización.', 12),
(1, 7, 21, 'a) Se cuenta con un proceso para la selección de sus proveedores basado en elementos objetivos como: confiabilidad, logística, disponibilidad y precio.', 1),
(1, 7, 21, 'b) Se cuenta con mecanismos para asegurar que el producto / servicio solicitado cumple con los requerimientos y especificaciones establecidas dentro de los documentos o fichas técnicas establecidas; así como en su caso, los ciclos de vida correspondientes.', 2),
(1, 7, 21, 'c) El proceso para evaluar y retroalimentar el desempeño de los proveedores se basa en el impacto sobre los procesos básicos.', 3),
(1, 7, 21, 'd) Se cuenta con prácticas en donde se involucra a los proveedores para definir proyectos orientados a mejorar la competitividad mutua.', 4),
(1, 8, 22, 'a) Se tienen identificados sus agentes contaminantes y/o responsabilidades ecológicas, derivadas de su operación.', 1),
(1, 8, 22, 'b) Se cuenta con procedimientos para cumplir con sus responsabilidades ecológicas y para evitar la contaminación del entorno.', 2),
(1, 9, 24, 'a) Se cuentan con procedimientos específicos para contrarrestar los efectos de acontecimientos traumáticos severos (Asaltos, accidentes, secuestros, lesiones, etc.)', 1),
(1, 9, 24, 'b) Se cuenta con procedimientos para identificar a los colaboradores afectados por algún acontecimiento traumático', 2),
(1, 9, 24, 'c) Se tienen identificados los puestos que requieren un esfuerzo físico o habilidad específica, además de que son informados a los colaboradores que los realizan desde su integración a la Organización.', 3),
(1, 9, 24, 'd) Se cuenta con procedimientos para evitar y actuar si existe algún riesgo de accidente en el Trabajo.', 4),
(1, 9, 24, 'e) Se cuenta con prácticas para fomentar una relación favorable con la comunidad Organizacional', 5),
(1, 9, 24, 'f) Se promueve y difunde la filosofía de la organización con la comunidad.', 6),
(1, 9, 24, 'g) Se cuenta con programas de prevención de violencia laboral dentro de la Organización', 7),
(1, 9, 24, 'h) Se cuenta con programas de prevención y promoción de la Salud dentro de la Organización', 8),
(1, 9, 25, 'i) Se cuenta con un descriptivo de puesto, en el que los Colaboradores saben exactamente cuáles son sus funciones y métricas de desempeño esperadas.', 9),
(1, 9, 25, 'j) Se cuenta con procedimientos y controles para los Colaboradores que son responsables de activos de valor.', 10),
(1, 9, 25, 'k) Se cuenta con mejores prácticas para fomentar una relación favorable entre colaboradores y la línea de mando', 11),
(1, 9, 25, 'l) Se cuenta con programas de Capacitación orientados a los factores psicosociales definidos de acuerdo con las necesidades de los puestos y del entorno organizacional', 12),
(1, 9, 25, 'm) Se cuenta con procesos formales de medición del desempeño de cada uno de los puestos y son informados a los Colaboradores mediante una sesión de retroalimentación', 13),
(1, 9, 26, 'n) Se cuenta con procesos o mejores prácticas relacionadas a las jornadas de trabajo (horas extra, días de descanso, días festivos)', 14),
(1, 9, 26, 'ñ) Se cuenta con procesos o mejores prácticas promocionadas por la Organización que contribuyan al bienestar familiar', 15),
(1, 9, 27, 'o) Se cuenta con procedimientos y/o mejores prácticas para gestionar los planes de carrera de acuerdo con la productividad individual y colectiva', 16),
(1, 10, 29, 'a) Se cuentan con procedimientos o mejores prácticas para actuar ante entornos imprevistos, complejos, ambiguos, frágiles o acontecimientos que impliquen un cambio Organizacional disruptivo.', 1),
(1, 10, 29, 'b) Al encontrarse dentro de entornos imprevistos, complejos, ambiguos, frágiles o acontecimientos que impliquen un cambio Organizacional disruptivo, se cuentan con los procedimientos o mejores prácticas para determinar las mejoras y/o habilidades que necesitan los colaboradores para seguir realizando sus actividades de forma eficaz y eficiente.', 2),
(1, 10, 29, 'c) Al encontrarse dentro de entornos imprevistos, complejos, ambiguos, frágiles o acontecimientos que impliquen un cambio Organizacional disruptivo, se cuentan con procedimientos o mejores prácticas de contención de factores psicosociales y/ salud organizacional.', 3),
(1, 10, 29, 'd) Al encontrarse dentro de entornos imprevistos, complejos, ambiguos, frágiles o acontecimientos que impliquen un cambio Organizacional disruptivo, se realizan procedimientos o mejores prácticas para contener y/o fortalecer la Inteligencia Emocional de los colaboradores.', 4);

-- Reactivar revisión de llaves foráneas
SET FOREIGN_KEY_CHECKS = 1;
